manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nickcoutsos
      url-base: https://github.com/nickcoutsos
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-nice-nano
      remote: nickcoutsos
      revision: master
    - name: zmk-paw3395-driver
      remote: badjeff
      revision: main
  self:
    path: config