# Pointer/Maus Support
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Hardware Treiber
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PAW3395=y

# Dieser Befehl braucht das CONFIG_ Präfix
CONFIG_ZMK_KSCAN_DIRECT_GPIO=y